### ISSUE TITLE
Feature proposal for basic curl like command

### ISSUE THREAD

**Issue by jthacker** [fhunleth/toolshed#50]
@fhunleth Do you think there is value in having a really simple HTTP get command within toolshed? I'd propose something along the lines of the following changes:
* Add httpget command to Toolshed.Net
* A signature like `httpget(url, options \\ []) -> nil`
  * `options` includes the following to start:
    * `dest` - defaults to :stdout, but could be set to a string to write to the filesystem
* Prints the result to the terminal

Future improvement could include:
* Other HTTP verbs, `httpput`, `httppost`, etc.
* Additional options to allow setting headers, proxies, etc.

If you think there is value in this, I can put a PR together.

**Comment by fhunleth** [comment]
Seems really useful to me. My main constraint has been that the utilities don't pull in too many external libraries. That's why I've been using `:httpc`. See https://github.com/fhunleth/toolshed/blob/main/lib/toolshed/http.ex.

As for location, `http.ex` is probably an easier place to put it.

Thanks!!

**Comment by fhunleth** [comment]
Fixed. See 1e86cdbf1f5bec9f4761d99dd3720ebb74d20807.
